config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root :to => 'landing#index'

  resources :users do
    resources :photos
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user

  has_attached_file :image
  validates_attachment :image, content_type: { content_type: /\Aimage\/.*\Z/ }
  
  validates :title, :presence => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!

  def index
    if current_user
      @photos = current_user.photos
    end
  end

  def new
   @photo = current_user.photos.new
  end

  def create
   @photo = current_user.photos.new(photo_params)
   if @photo.save
    flash[:notice] = "Successfully added new photo!"
    redirect_to user_photos_path
   else
    flash[:alert] = "Error adding new photo!"
    render :new
   end
  end

private
  def photo_params
   params.require(:photo).permit(:title, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/landing/index.html.erb
<div class="row justify-content-center mt-4">
  <div class="col-9">
    <div class="card card-body text-center">
      <h1 class="display-3">Welcome to PicStore</h1>
      <p class="lead">The cloud storage solution for your all your photos!</p>
      <hr class="my-4">
      <p>It's easy to use! Just <%= link_to "sign up", new_user_registration_path %> and start uploading!</p>
    </div>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
      <a class="navbar-brand ml-2" href="/">PicStore</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <ul class="navbar-nav mr-auto">
            <% if user_signed_in? %>
              <li class="nav-item ml-2 mr-2 mt-1 mb-1">
                <%= link_to "My Photos", user_photos_path(current_user), :class => "nav-link text-white link-text" %>
              </li>
              <li class="nav-item ml-2 mr-2 mt-1 mb-1">
                <%= link_to "Upload Photos", new_user_photo_path(current_user), :class => "nav-link text-white link-text" %>
              </li>
            <% end %>
          </ul>
        </ul>

        <ul class="navbar-nav ml-auto">
          <li class="nav-item ml-2 mr-2 mt-1 mb-1">
            <% if user_signed_in? %>
              <%= link_to "Logout, #{current_user.email}", destroy_user_session_path, method: :delete, :class => "btn text-white nav-link text-light link-text"%>
            <% else %>
              <%= link_to "Login", new_user_session_path, :class => "btn btn-primary text-white nav-link text-light link-text"%>
          </li>
          <li class="nav-item ml-2 mr-2 mt-1 mb-1">
              <%= link_to "Sign Up", new_user_registration_path, :class => "btn btn-light text-dark nav-link link-text" %>
            <% end %>
          </li>
        </ul>
      </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PicStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/nav" %>
    <div class="row justify-content-center">
      <div class="col-6">
        <% flash.each do |key, value| %>
          <% case key %>
          <% when "notice" %>
            <% type = 'success' %>
          <% when "alert" %>
            <% type = 'danger' %>
          <% else %>
            <% type = 'primary' %>
          <% end %>
          <div class="alert alert-<%= type %>">
            <%= value %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        <% end %>
      </div>
    </div>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/photos/index.html.erb
<div class="row justify-content-center">
  <div class="col-12">
    <div class="card card-body">
        <% if @photos.any? %>
          <h1>Your Photos</h1>
          <% @photos.each_slice(3) do |photos_row| %>
            <div class="row">
              <% photos_row.each do |photo| %>
                <div class="col-lg-4 col-sm-12 mb-2">
                  <%= link_to image_tag(photo.image.url, class: 'img-fluid'), photo.image.url, target: '_blank' %>
                </div>
              <% end %>
            </div>
          <% end %>
        <% else %>
          <h3>No Photos Yet! Upload your first image <%= link_to "now", new_user_photo_path %>!</h3>
        <% end %>
    </div>
  </div>
</div>

app/views/photos/new.html.erb
<div class="row justify-content-center">
  <div class="col-6">
    <div class="card card-body">
      <h1>Upload Photo</h1>
      <%= form_for [current_user, @photo], html: { multipart: true } do |f| %>
        <% if @photo.errors.any? %>
          <div id="error_explanation">
            <h2>
              <%= "#{pluralize(@photo.errors.count, "error")} prohibited this photo from being saved:" %>
            </h2>
            <ul>
              <% @photo.errors.full_messages.each do |msg| %>
                <li>
                  <%= msg %>
                </li>
                <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group row">
          <%= f.label "Title:", class: 'col-sm-2 col-form-label' %>
          <div class="col-sm-10">
            <%= f.text_field :title, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.file_field :image %>
        </div>

        <div class="form-group">
          <%= f.submit 'Upload Photo', class: 'btn btn-default' %>
        </div>
      <% end %>
    </div>
  </div>
</div>